# TODO: remove the "payonline-test" special case
openshift_namespace: >-
  {{ "payonline-test" if inventory_environment == "preprod"
     else "payonline-" + inventory_environment }}

keybase_secrets: >-
  {{       _keybase_secrets_prod    if inventory_environment == "prod"
      else _keybase_secrets_preprod if inventory_environment == "preprod"
      else None }}
_keybase_secrets_prod: >-
    {{ lookup('file', '/keybase/team/epfl_payonline.prod/secrets.yml') | from_yaml }}
_keybase_secrets_preprod: >-
    {{ lookup('file', '/keybase/team/epfl_payonline.preprod/secrets.yml') | from_yaml }}

payonline_hostname: >-
  {{ "payonline.epfl.ch" if inventory_environment == "prod"
      else "payonline-" + inventory_environment + ".epfl.ch" }}
openshift_image_tag: >-
  {{ "prod" if inventory_environment == "prod" else "develop" }}
openshift_image: >-
  docker-registry.default.svc:5000/{{ openshift_namespace }}/payonline:{{ openshift_image_tag }}

# TODO: metaprogram this?
payonline_env_from_configmap:
   - name: TEQUILA_HOST
     valueFrom:
       configMapKeyRef:
         name: payonline-conf
         key: TEQUILA_HOST
   - name: MOCK_ORACLE
     valueFrom:
       configMapKeyRef:
         name: payonline-conf
         key: MOCK_ORACLE
   - name: SITE_URL
     valueFrom:
       configMapKeyRef:
         name: payonline-conf
         key: SITE_URL
   - name: E2EM_LINE
     valueFrom:
       configMapKeyRef:
         name: payonline-conf
         key: E2EM_LINE
payonline_mail_sf_recipients:
  preprod:
    - dominique.quatravaux@epfl.ch
    - nicolas.borboen@epfl.ch
  prod:
    - marc.fromentin@epfl.ch
    - pascal.schweingruber@epfl.ch
    - pierre.fournier@epfl.ch
    - barbara.bouteiller@epfl.ch
    - ana.henriques@epfl.ch
