openshift_namespace: >-
  {{ "payonline-" + inventory_environment }}

keybase_secrets: >-
  {{       _keybase_secrets_prod    if inventory_environment == "prod"
      else _keybase_secrets_preprod if inventory_environment == "test"
      else None }}
_keybase_secrets_prod: >-
    {{ lookup('file', '/keybase/team/epfl_payonline.prod/secrets.yml') | from_yaml }}
_keybase_secrets_preprod: >-
    {{ lookup('file', '/keybase/team/epfl_payonline.preprod/secrets.yml') | from_yaml }}

payonline_hostname: >-
  {{ "payonline.epfl.ch" if inventory_environment == "prod"
      else "payonline-preprod.epfl.ch" if inventory_environment == "test"
      else "localhost" }}
openshift_image_tag: >-
  {{ "prod" if inventory_environment == "prod" else "develop" }}
openshift_image: >-
  docker-registry.default.svc:5000/{{ openshift_namespace }}/payonline:{{ openshift_image_tag }}

payonline_superuser_group: >-
  {{ "payonline-fi" if inventory_environment == "prod" else "payonline-ops" }}

payonline_mail_sf_recipients:
  test:
    - dominique.quatravaux@epfl.ch
    - nicolas.borboen@epfl.ch
  prod:
    - pascal.schweingruber@epfl.ch
    - pierre.fournier@epfl.ch
    - barbara.bouteiller@epfl.ch
    - ana.henriques@epfl.ch

payonline_extract_transaction_cron_schedule: >-
  05 0 * * *
