# TODO: remove the "payonline-test" special case
openshift_namespace: >-
  {{ "payonline-test" if inventory_environment == "preprod"
     else "payonline-" + inventory_environment }}
keybase_secrets:
  prod: >-
    {{ lookup('file', '/keybase/team/epfl_payonline.prod/secrets.yml') | from_yaml }}
  # TODO: have preprod secrets, too
payonline_hostname: >-
  {{ "payonline.epfl.ch" if inventory_environment == "prod"
      else "payonline-" + inventory_environment + ".epfl.ch" }}
openshift_image_tag: >-
  {{ "prod" if inventory_environment == "prod" else "develop" }}
openshift_image: >-
  docker-registry.default.svc:5000/{{ openshift_namespace }}/payonline:{{ openshift_image_tag }}

payonline_mail_sf_recipients:
  preprod:
    - dominique.quatravaux@epfl.ch
    - nicolas.borboen@epfl.ch
  prod:
    - marc.fromentin@epfl.ch
    - pascal.schweingruber@epfl.ch
    - pierre.fournier@epfl.ch
    - barbara.bouteiller@epfl.ch
    - ana.henriques@epfl.ch
